CREATE OR REPLACE FUNCTION HASSUFFICIENTBALANCE(
    ID IN ACCOUNTS.ACCOUNTID%TYPE,
    AMOUNT IN TRANSACTIONS.AMOUNT%TYPE
) RETURN VARCHAR2 IS
    BAL ACCOUNTS.BALANCE%TYPE;
BEGIN
    SELECT
        BALANCE INTO BAL
    FROM
        ACCOUNTS
    WHERE
        ACCOUNTID=ID;
    IF BAL>=AMOUNT THEN
        RETURN 'TRUE';
    ELSE
        RETURN 'FALSE';
    END IF;
END;
