CREATE OR REPLACE FUNCTION CALCULATEMONTHLYINSTALLMENT(
    LOAN IN LOANS.LOANAMOUNT%TYPE,
    RATE IN LOANS.INTERESTRATE%TYPE,
    DURATION IN NUMBER
) RETURN NUMBER IS
    MONTHLY_RATE NUMBER;
    TOTAL_MONTHS NUMBER;
BEGIN
    MONTHLY_RATE := (RATE / 12) / 100;
    TOTAL_MONTHS := DURATION * 12;
    RETURN FLOOR(LOAN * MONTHLY_RATE * POWER(1 + MONTHLY_RATE, TOTAL_MONTHS) / (POWER(1 + MONTHLY_RATE, TOTAL_MONTHS) - 1));
END;
