CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus(DEPT IN EMPLOYEES.DEPARTMENT%TYPE,BONUS IN NUMBER) IS
BEGIN
    UPDATE EMPLOYEES
    SET SALARY=FLOOR(SALARY+(SALARY*(BONUS/100)))
    WHERE DEPARTMENT=DEPT;
END;
