CREATE OR REPLACE PROCEDURE TRANSFERFUNDS(
    FROM_ACCOUNT IN ACCOUNTS.ACCOUNTID%TYPE,
    TO_ACCOUNT IN ACCOUNTS.ACCOUNTID%TYPE,
    AMOUNT IN ACCOUNTS.BALANCE%TYPE
) IS
    BAL ACCOUNTS.BALANCE%TYPE;
BEGIN
    SELECT
        BALANCE INTO BAL
    FROM
        ACCOUNTS
    WHERE
        ACCOUNTID=FROM_ACCOUNT;
    IF BAL>=AMOUNT THEN
        UPDATE ACCOUNTS
        SET
            BALANCE=BALANCE-AMOUNT
        WHERE
            ACCOUNTID=FROM_ACCOUNT;
        UPDATE ACCOUNTS
        SET
            BALANCE=BALANCE+AMOUNT
        WHERE
            ACCOUNTID=TO_ACCOUNT;
    ELSE
        DBMS_OUTPUT.PUT_LINE('INSUFFICIENT BALANCE.');
    END IF;
END;
