CREATE OR REPLACE PROCEDURE SAFETRANSFERFUNDS(
    FUND ACCOUNTS.BALANCE%TYPE,
    TOID ACCOUNTS.ACCOUNTID%TYPE,
    FROMID ACCOUNTS.ACCOUNTID%TYPE
) IS
    BAL ACCOUNTS.BALANCE%TYPE;
BEGIN
    SELECT
        BALANCE INTO BAL
    FROM
        ACCOUNTS
    WHERE
        ACCOUNTID=FROMID;
    IF FUND>BAL THEN
        RAISE_APPLICATION_ERROR(-20001, 'THE ACCOUNT FROM WHICH THE FUND HAS TO BE TRANSFERRED MUST HAVE SUFFICIENT BALANCE.');
    END IF;
    UPDATE ACCOUNTS
    SET
        BALANCE=BALANCE-FUND
    WHERE
        ACCOUNTID=FROMID;
    UPDATE ACCOUNTS
    SET
        BALANCE=BALANCE+FUND
    WHERE
        ACCOUNTID=TOID;
END;
