CREATE OR REPLACE PROCEDURE ADDNEWCUSTOMER(
    ID IN CUSTOMERS.CUSTOMERID%TYPE,
    NAME IN CUSTOMERS."NAME"%TYPE,
    DOB IN CUSTOMERS.DOB%TYPE,
    BALANCE IN CUSTOMERS.BALANCE%TYPE,
    LASTMODIFIED IN CUSTOMERS.LASTMODIFIED%TYPE,
    ISVIP IN CUSTOMERS.ISVIP%TYPE
) IS
    COUNTRECORD NUMBER;
BEGIN
    SELECT
        COUNT(*) INTO COUNTRECORD
    FROM
        CUSTOMERS
    WHERE
        CUSTOMERID=ID;
    IF COUNTRECORD>0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'CUSTOMER ID '
                                        ||ID
                                        ||' ALREADY EXISTS IN THE RELATION.');
    END IF;

    INSERT INTO CUSTOMERS VALUES(
        ID,
        NAME,
        DOB,
        BALANCE,
        LASTMODIFIED,
        ISVIP
    );
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR CODE: '
                             ||SQLCODE);
        DBMS_OUTPUT.PUT_LINE('ERROR MESSEGE: '
                             ||SQLERRM);
END;
